version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9 # Or another suitable runtime if needed for helper scripts
    commands:
      # Install Terraform
      - curl -LO https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip # Check for the latest stable version on Terraform's website
      - unzip terraform_1.8.5_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - rm terraform_1.8.5_linux_amd64.zip
      - terraform version

  pre_build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init

  build:
    commands:
      - echo "Planning Terraform changes..."
      - terraform plan -out=tfplan # Good practice to save the plan
      - echo "Applying Terraform changes to create EC resource..."
      - terraform apply -auto-approve tfplan # Apply the saved plan, -auto-approve for CI/CD

  post_build:
    commands:
      - echo "Terraform apply completed."
      # You might want to output some resource attributes here, e.g.,
      # - terraform output <your_ec_resource_attribute>

artifacts:
  files:
    - '**/*' # Optionally include any generated files like the tfplan
  base-directory: .
