version: 0.2
phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - which terraform || (
          wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip &&
          unzip /tmp/terraform.zip -d /usr/local/bin
        )
      - terraform --version
  build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init
      - echo "Running Terraform Plan..."
      - terraform plan -no-color -out=plan.out
artifacts:
  files:
    - plan.out
