version: 1.0
metadata:
  pipeline:
    name: CreateEC2Pipeline
    region: us-east-1 # Ensure this matches your AWS region
    roleArn: "arn:aws:iam::418295695531:role/cd-iam" # Replace with your CodePipeline service role ARN
stages:
  - name: Source
    actions:
      - name: CheckoutSource
        actionTypeId:
          category: Source
          owner: AWS
          provider: CodeCommit # Or GitHub, S3, etc.
          version: "1"
        configuration:
          RepositoryName: "your-terraform-repo" # Replace with your repository name
          BranchName: "main" # Or your desired branch
        outputArtifacts:
          - Name: TerraformSource

  - name: Plan
    actions:
      - name: TerraformPlan
        actionTypeId:
          category: Build
          owner: AWS
          provider: CodeBuild
          version: "1"
        inputArtifacts:
          - Name: TerraformSource
        outputArtifacts:
          - Name: TerraformPlanOutput
        configuration:
          ProjectName: "MyWebApp" # Replace with your CodeBuild project name

  - name: Apply
    actions:
      - name: TerraformApply
        actionTypeId:
          category: Build
          owner: AWS
          provider: CodeBuild
          version: "1"
        inputArtifacts:
          - Name: TerraformSource
          - Name: TerraformPlanOutput # Optional, but can be used for confirmation
        configuration:
          ProjectName: "MyWebApp" # Replace with your CodeBuild project name
