# Example using a generic CI/CD syntax

stages:
  - FormatAndValidate
  - Plan
  - Apply

format_and_validate:
  stage: FormatAndValidate
  script:
    - terraform fmt -check
    - terraform validate

plan:
  stage: Plan
  script:
    - terraform init
    - terraform plan -no-color -out=tfplan

apply:
  stage: Apply
  script:
    - terraform init
    - terraform apply -auto-approve -no-color tfplan
  # Add a conditional to only run on the main branch, for example
  # only:
  #   refs:
  #     - main
